server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: course-registration-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course_registration
    username: root
    password: dongnv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  batch:
    job:
      enabled: false  # tắt việc job tự động chạy bằng JobLauncherApplicationRunner
    datasource:
      url: jdbc:mysql://localhost:3306/batch_db
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc:
      initialize-schema: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: dongnv4724@gmail.com
    password: kyxk gutl wfbh ihgp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  account-admin:
    username: admin
    password: admin
jwt:
  signer-key: pEKWBDkFc9GHbPGrFK9S0Ao4ak5bQHx6FhzoMJv78cnqA5+8pHiAAq+cw3t1+454
  issuer: DongBatTu
  expired: 60 # minutes


