server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: course-registration-management

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/course_registration}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_USERNAME:dongnv}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false  # tắt việc job tự động chạy bằng JobLauncherApplicationRunner

  mail:
    host: smtp.gmail.com
    port: 587
    username: dongnv4724@gmail.com
    password: ${MAIL_PASSWORD:kyxk gutl wfbh ihgp}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  task: # Số thread chạy scheduling task
    scheduling:
      pool:
        size: 5

  thymeleaf:
    cache: false

jwt:
  signer-key: pEKWBDkFc9GHbPGrFK9S0Ao4ak5bQHx6FhzoMJv78cnqA5+8pHiAAq+cw3t1+454
  issuer: VietIs
  expired: 45 # minutes
  expired-with-remember-me: 4320 # 3 days
  cookie-name: access_token


